### PR TITLE
Update to game version 2.4

### PR DESCRIPTION
**Pull request by IceDynamix**
the way that trailblazer data is sent has been changed. data is now sent in `GetMultiPathAvatarInfoScRsp`, which is shared between both the trailblazer and march 7th. we cannot exclude the possibility of other characters receiving path changes, so i need to look into how to structure this properly.

there will be two releases for game version 2.4

- `v0.1.8` will be the release with this pull request, adapted to game version 2.4
- `v0.1.9` will embed the required data into the executable rather than fetching them from online

### CODE REVIEW

**Comment by emmachase** [comment]
2254e77ce15baa35648126e853abeb271aa1dc13 implements support for reading multipath characters. (commit base is parented on this draft PR)

**Comment by IceDynamix** [comment]
convenient, thanks! do you mind making a pr or do you want me to cherry-pick the commit? @emmachase

**Comment by emmachase** [comment]
Forgot I could open PR's against other branches haha. Yeah I've opened one #48

**Comment by IceDynamix** [comment]
given the urgency of the update, i will create a release without multipath characters support for now. v0.1.9 will contain both multipath character support and the local db

**Pull request merged**
